### ISSUE TITLE
When adding new ping probe, "save" is disabled

### ISSUE THREAD

**Issue by mem** [grafana/worldping-app#27]
Add a new check.

Don't click on check type.

Type "grafana.com" in the target.

Select a probe.

The "save" button is not enabled.

Click the check type, select something, click again, go back to PING. Now save is enabled.

**Comment by woodsaj** [comment]
this is due to the the form not being re-rendered when the probe locations are updated. I will have a fix pushed shortly.

**Comment by mem** [comment]
This is fixed in master, thanks!
